# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end

  # Salt master
  config.vm.define "master" do |node|
    node.vm.hostname = "master"
    node.vm.network :private_network, ip: "192.168.33.10"
    node.vm.network "forwarded_port", guest: 3000, host: 3000

    node.vm.synced_folder "../salt/", "/srv/salt"
    node.vm.synced_folder "../pillar/", "/srv/pillar"

    # salt-master provisioning
    node.vm.provision :salt do |salt|
      salt.log_level = 'all'
      salt.install_master = true
      salt.run_highstate = false
      salt.master_key = 'keys/master.pem'
      salt.master_pub = 'keys/master.pub'

      salt.minion_config = "configs/minion"
      salt.minion_key = 'keys/master.pem'
      salt.minion_pub = 'keys/master.pub'

      salt.run_highstate = true

      salt.seed_master = {
        'node01' => 'keys/node01.pub',
        'node02' => 'keys/node02.pub',
        'master' => 'keys/master.pub'
      }
    end
  end

  config.vm.define "node01" do |node|
    node.vm.hostname = "node01"
    node.vm.network :private_network, ip: "192.168.33.20"

    # salt-minion provisioning
    node.vm.provision :salt do |salt|
      salt.log_level = 'all'
      salt.minion_config = "configs/minion"
      salt.minion_key = 'keys/node01.pem'
      salt.minion_pub = 'keys/node01.pub'

      salt.run_highstate = true

    end
  end

  config.vm.define "node02" do |node|
    node.vm.hostname = "node02"
    node.vm.network :private_network, ip: "192.168.33.30"

    # salt-minion provisioning
    node.vm.provision :salt do |salt|
      salt.log_level = 'all'
      salt.minion_config = "configs/minion"
      salt.minion_key = 'keys/node02.pem'
      salt.minion_pub = 'keys/node02.pub'

      salt.run_highstate = true

    end
  end
end
